### ISSUE TITLE
the passwd of your docker

### ISSUE THREAD

**Issue by yuzhenbo** [Tiryoh/docker_ros-indigo-desktop#1]
when i launch your docker, i find it is not root by default, when i use sudo , i found  passwd is necessary, so i do not know your passwd, and i can not do anything i want in it

**Comment by Tiryoh** [comment]
@yuzhenbo Thanks for your comment.
The default user of this container is `ubuntu`, and the password is also set as `ubuntu`.
It is configured here:
https://github.com/Tiryoh/docker_ros-indigo-desktop/blob/master/Dockerfile#L14

**Comment by Tiryoh** [comment]
added password to `README.md` on 3d8649bded0936f319b7f991af45da81ed9bb2b2
