### ISSUE TITLE
arm46v8 based docker with ubuntu14.04 and indigo

### ISSUE THREAD

**Issue by SYSUHPK** [Tiryoh/docker_ros-indigo-desktop#2]
I have a question whether there are any arm46v8 based docker with ubuntu14.04 and indigo

**Comment by Tiryoh** [comment]
Seems like there are only docker images of distro versions after than Indigo for arm64v8.
https://github.com/docker-library/official-images/blob/master/library/ros

Ubuntu 14.04 image for arm64v8 has been published, so I think it is possible to build your image for Indigo.
https://hub.docker.com/r/arm64v8/ubuntu/

**Comment by SYSUHPK** [comment]
Thanks a lot. In fact, I have tried everything you said before. I found the image of ubuntu14.04 based on arm64v8 and successfully installed it. But when I installed indigo on this, I was always prompted "could not load package ros-indigo-desktop",that's why I wanted to ask you if you have an indigo image that includes ubuntu14.04+indigo

**Comment by Tiryoh** [comment]
I see, maybe, OSRF's repository does not distribute the binary package of ROS Indigo for arm64v8.
Unfortunately, I don't use Ubuntu 14.04 anymore, so I don't have a plan to test building ROS Indigo on new devices.
How about tiring to use ROS Kinetic on Ubuntu 16.04 or ROS Melodic on Ubuntu 18.04? The date of EOL for ROS Indigo is next month.
http://wiki.ros.org/Distributions

**Comment by SYSUHPK** [comment]
Thank you very much for your suggestion. In fact, I had successfully installed ubuntu16.04+kinetic before, but there was a problem while using maplab. The solution I got on github was that ubuntu14.04+indigo could solve it, so I wanted to have a try. Thank you very much for your proposal. Maybe I can try 18.04+ Melodic，i hope a higher version can solve this problem

**Comment by Tiryoh** [comment]
> In fact, I had successfully installed ubuntu16.04+kinetic before, but there was a problem while using maplab.

Oh, that's too bad...
I hope everything turns out well.

**Comment by SYSUHPK** [comment]
Anyway, thank you very much for your help.
